name: Presubmit

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  presubmit:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16'
    - name: setup
      run: |
        npm install
    - name: presubmit
      run: |
        eslint --ext .js,.jsx,.ts,.tsx src test